### ISSUE TITLE
Use XDG base directory specification for paths

### ISSUE THREAD

**Issue by BrainDamage** [alejandrogallo/papis#1] opened 2017-09-13 09:42 UTC
In order to cleanup dotfile clutter, making backup easier and giving a standard, [XDG Base directory standard](https://standards.freedesktop.org/basedir-spec/latest/) was made.
The standard uses a common prefix for user dirs having either by default a well known path or either an env var chosen by the user, allowing flexibility if necessary ( env var can be overridden on a per-program basis if one needs so ).
Implementation of the standard should be rather easy, if necessary there's a [sample library from freedesktop itself](https://freedesktop.org/wiki/Software/pyxdg/).
For a third party project that tracks adoption, see the [Arch Wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support).

**Comment by alejandrogallo** [comment] 2017-09-13 15:12
Hi, yes, I have been wanting to do this for a while, I'll get to it since it is the first issue!

**Comment by alejandrogallo** [comment] 2017-09-13 22:20
Support has been added for the cache (``XDG_CACHE_HOME``) and user's configuration files
``XDG_CONFIG_HOME`` and ``XDG_CONFIG_DIRS``. The user data is missing since it is not really used yet in ``papis``, after doing some further tests and implement unittesting I will then close the issue. You are welcome to test it in you workflow!

**Comment by mftrhu** [comment] 2017-09-14 11:44
There seems to be a bug in this implementation I stumbled upon while trying out the last version as of 13:07 CEST (`pip uninstall papis`; `git clone`; `sudo make install`).

Running `papis edit` gave me the following traceback:

```
```

**Comment by alejandrogallo** [comment] 2017-09-14 20:35
I have to check this in more detail, sorry for the delay! But it can be the reason that you say with the
order of directories ;)

**Comment by alejandrogallo** [comment] 2017-09-14 22:33
Yes you are totally right, the problem is that papis looks for configuration files in the following paths:
``$XDG_CONFIG_DIRS``, ``$XDG_CONFIG_HOME`` and ``$HOME``, if there is one ``$dir/papis`` 
in place then it takes that one, if not it tries to create one default one. The default before was the
first in the upper list of directories, which in your case would have been ``/etc/xdg`` since you set ``$XDG_CONFIG_DIRS`` accordingly, the default should instead be ``$XDG_CONFIG_HOME``, excellent catch!

**Comment by alejandrogallo** [comment] 2017-09-15 22:58
Since I do not find any other bugs, I will close for now this issue.

**Closed by alejandrogallo** 2017-09-15 22:58 UTC
Labels: enhancement
